=== Avijn/DataProcessingMLB/Opdracht 1/xml/TeamRanking.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
		   elementFormDefault="qualified"
		   attributeFormDefault="unqualified">
	<xs:element name="rankingList">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ranking" type="rankingType" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="rankingType">
		<xs:sequence>
			<xs:element name="id" type="xs:int" minOccurs="1" maxOccurs="1"></xs:element>
			<xs:element name="gameNumber" type="xs:int" minOccurs="1" maxOccurs="1"></xs:element>
			<xs:element name="year" type="xs:int" minOccurs="1" maxOccurs="1"></xs:element>
			<xs:element name="date" type="xs:string" minOccurs="1" maxOccurs="1"></xs:element>
			<xs:element name="team" type="xs:string" minOccurs="1" maxOccurs="1"></xs:element>
			<xs:element name="home_away" type="xs:string" minOccurs="1" maxOccurs="1"></xs:element>
			<xs:element name="opp" type="xs:string" minOccurs="1" maxOccurs="1"></xs:element>
			<xs:element name="win_or_lose" type="xs:string" minOccurs="1" maxOccurs="1"></xs:element>
			<xs:element name="rank" type="xs:int" minOccurs="1" maxOccurs="1"></xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== Avijn/DataProcessingMLB/Opdracht 1/xml/TeamRanking.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<rankingList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			  xsi:noNamespaceSchemaLocation="TeamRanking.xsd">
	<ranking>
		<id>
			0
		</id>
		<gameNumber>
			1
		</gameNumber>
		<year>
			2013
		</year>
		<date>
			2013-04-01
		</date>
		<team>
			Arizona
		</team>
		<home_away>
			home
		</home_away>
		<opp>
			Colorado
		</opp>
		<win_or_lose>
			W
		</win_or_lose>
		<rank>
			1
		</rank>
	</ranking>
</rankingList>
