=== Avijn/DataProcessingMLB/DataProcessingMLB/DataProcessingMLB/xml/Beercost.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
		   elementFormDefault="qualified"
		   attributeFormDefault="unqualified">
	<xs:element name="beercostList">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="beercost" type="beercostType" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="beercostType">
		<xs:sequence>
			<xs:element name="year" type="xs:int" minOccurs="1" maxOccurs="1" />
			<xs:element name="team" type="xs:string" minOccurs="1" maxOccurs="1" />
			<xs:element name="nickname" type="xs:string" minOccurs="1" maxOccurs="1" />
			<xs:element name="city" type="xs:string" minOccurs="1" maxOccurs="1" />

			<xs:element name="price" type="priceType" minOccurs="1" maxOccurs="1" />
				
				<!--<xs:simpleType>
					<xs:restriction base="xs:decimal">
						<xs:minInclusive value="0.0" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>-->

			<xs:element name="size" type="sizeType" minOccurs="1" maxOccurs="1" />
			<xs:element name="price_per_Ounce" type="price_per_ounceType" minOccurs="1" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="priceType">
		<xs:simpleContent>
			<xs:extension base="xs:decimal">
				<xs:attribute name="valuta" type="xs:string" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>	
	
	<xs:complexType name="sizeType">
		<xs:simpleContent>
			<xs:extension base="xs:decimal">
				<xs:attribute name="in" type="xs:string" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	
	<xs:complexType name="price_per_ounceType">		
		<xs:sequence>
			<xs:element name="price" type="price_per_ounceType_"/>
		</xs:sequence>
	<xs:attribute></xs:attribute>
	</xs:complexType>
	
	<xs:complexType name="price_per_ounceType_Attribute">
		<xs:complexContent>
			<xs:extension base="xs:string">
				<xs:attribute name="valuta" type="price_per_ounce_Attribute_Valuta" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
		<!--<xs:simpleContent>
		<xs:sequence>
			<xs:element name="price_per_ounce_Attribute_Valuta" type="price_per_ounce_Attribute_Valuta" />
			<xs:element name="price_per_ounce" type="price_per_ounceType_" />
				
		</xs:sequence>
			</xs:simpleContent>

		--><!--<xs:attribute name="valuta" type="price_per_ounce_Attribute_Valuta" />--><!--
	</xs:complexType>-->
	
	<xs:simpleType name="price_per_ounceType_">
		<xs:restriction base="xs:decimal">
			<xs:minInclusive value="0.0" />
		</xs:restriction>
	</xs:simpleType>

	<!--<xs:complexType name="price_per_ounceType_Attribute">
		<xs:simpleContent>
			<xs:extension base="xs:decimal">
				<xs:attribute name="valuta" type="xs:string"/>
				<xs:attribute name="in" type="xs:string"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>-->
	
	<xs:complexType name="price_per_ounce_Attribute_Valuta">
		<xs:simpleContent>
			<xs:extension base="xs:decimal">
				<xs:attribute name="valuta" type="xs:string"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>


</xs:schema>

=== Avijn/DataProcessingMLB/DataProcessingMLB/DataProcessingMLB/xml/Beercost.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<beercostList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
			  xsi:noNamespaceSchemaLocation="Beercost.xsd">
	<beercost>
		<year>
			2013
		</year>
		<team>
			<teamName>
				Arizona Diamondbacks
			</teamName>
			<nickname>
				Diamondbacks
			</nickname>
			<city>
				Arizona
			</city>
		</team>
		<beer valuta="Dollar" unit="Ounce">
			<price>
				4.0
			</price>
			<size>
				14.0
			</size>
			<price_per_Ounce >
				0.2857142857142857
			</price_per_Ounce>
		</beer>
	</beercost>
</beercostList>
