=== Avijn/DataProcessingMLB/DataProcessingMLB/DataProcessingMLB/xml/TeamRanking.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
		   elementFormDefault="qualified"
		   attributeFormDefault="unqualified">
	<xs:element name="rankingList">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ranking" type="rankingType" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="rankingType">
		<xs:sequence>
			<xs:element name="id" type="xs:int" minOccurs="1" maxOccurs="1"></xs:element>
			<xs:element name="year" type="yearType" minOccurs="1" maxOccurs="1" />
			<xs:element name="rank" type="rankType" minOccurs="1" maxOccurs="1" />
			<xs:element name="matchDetails" type="matchDetailsType" minOccurs="1" maxOccurs="1"  />
			<xs:element name="match" type="matchType" minOccurs="1" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="matchDetailsType">
		<xs:sequence>
			<xs:element name="date" type="xs:string" minOccurs="1" maxOccurs="1"></xs:element>
			<xs:element name="team" type="teamType" minOccurs="1" maxOccurs="1"></xs:element>
			<xs:element name="opp" type="teamType" minOccurs="1" maxOccurs="1"></xs:element>
		</xs:sequence>
	</xs:complexType>
	
	<xs:simpleType name="teamType">
		<xs:restriction base="xs:string">
			<xs:pattern value="[A-Z][a-z]" />
			<xs:maxLength value="50" />			
		</xs:restriction>
	</xs:simpleType>
	

	<xs:complexType name="matchType">
		<xs:sequence>
			<xs:element name="gameNumber" type="xs:int" minOccurs="1" maxOccurs="1">
			</xs:element>
			<xs:element name="home_away" type="xs:string" minOccurs="1" maxOccurs="1"></xs:element>
			<xs:element name="win_or_lose" type="xs:string" minOccurs="1" maxOccurs="1"></xs:element>
		</xs:sequence>
	</xs:complexType>


	<xs:simpleType name="rankType">
		<xs:restriction base="xs:int">
			<xs:minInclusive value="0" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="yearType">
		<xs:restriction base="xs:int">
			<xs:minInclusive value="2010" />
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== Avijn/DataProcessingMLB/DataProcessingMLB/DataProcessingMLB/xml/TeamRanking.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<rankingList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			  xsi:noNamespaceSchemaLocation="TeamRanking.xsd">
	<ranking>
		<id>
			0
		</id>
		<year>
			2013
		</year>
		<rank>
			1
		</rank>
		<matchDetails>
			<date>
				2013-04-01
			</date>
			<team>
				Arizona
			</team>
			<opp>
				Colorado
			</opp>
		</matchDetails>
		<match>
			<gameNumber>
				1
			</gameNumber>
			<home_away>
				home
			</home_away>
			<win_or_lose>
				W
			</win_or_lose>
		</match>
	</ranking>
</rankingList>
